### ISSUE TITLE
Login Basic UI Design

### ISSUE THREAD

**Issue by alfonsusac** [alfonsusac/devscale-eventmaker#31]

**Comment by alfonsusac** [comment]
### Requirement
- [x] Create basic layout using the following image
- [x] Please post the screenshot of your browser after implementing the design.
- [x] Using 100% zoom (Cmd + 0) or (Ctrl + 0)

![Image](https://github.com/alfonsusac/devscale-eventmaker/assets/20208219/0bca0b58-c055-4b70-8d63-84c082adfcf1)

**Comment by rizaardiyanto1412** [comment]
@alfonsusac 
Recording: https://www.loom.com/share/70b6ff021f854fa2878f27b63da62a63

I want to create new branch for this, but my prev change (https://github.com/alfonsusac/devscale-eventmaker/pull/33) has not approved yet.

And I dont know how to make changes when the element is not there yet.

So I combined this to that PR. 

This is my commit https://github.com/alfonsusac/devscale-eventmaker/pull/33/commits/ad565ba6fbcad527355a23569fe42b27edc1be4b

**Comment by alfonsusac** [comment]
its ok to combine PR, thanks for working
