### ISSUE TITLE
Install a react-hot-toast

### ISSUE THREAD

**Issue by alfonsusac** [alfonsusac/devscale-eventmaker#32]
- [x] make sure Toaster is working

**Comment by rizaardiyanto1412** [comment]
@alfonsusac  This was fullfil in this commit. 
https://github.com/alfonsusac/devscale-eventmaker/pull/33/commits/9bfda078d941f7ad403a4a6ed6343d7c0e4a6aa6

**Comment by alfonsusac** [comment]
Hi @rizaardiyanto1412 please create another branch in main and add the react-hot-toast in there. After successfully merging it, only then you can pull `main` from your UI branch.

This way if UI branch is still in review, others can still use the react hot toast 👍
