### ISSUE TITLE
Register Basic UI Design

### ISSUE THREAD

**Issue by alfonsusac** [alfonsusac/devscale-eventmaker#37]
### Requirement
- [x] Create basic layout using the following image
- [x] Please post the screenshot of your browser after implementing the design.
- [x] Using 100% zoom (Cmd + 0) or (Ctrl + 0)

![Image](https://github.com/alfonsusac/devscale-eventmaker/assets/20208219/1c5c1ad4-aa4d-412b-a340-b2a29170d17b)

**Comment by ilmi** [comment]
for this issue, please refer to https://github.com/alfonsusac/devscale-eventmaker/pull/42
