### ISSUE TITLE
"Create Event" Basic UI

### ISSUE THREAD

**Issue by alfonsusac** [alfonsusac/devscale-eventmaker#44]
- [x] Create a page in `src/dashboard/create/page.js
- [x] Create a basic form and 3 form input + a submit button and template `handleSubmitButton` function
- [x] Create a "back" button that redirects to /dashboard
- [x] Only use basic UI (we really need MVP to be done :') )

**Comment by ilmi** [comment]
kindly refer to https://github.com/alfonsusac/devscale-eventmaker/pull/47
