### ISSUE TITLE
Delete Page: delete page should not have a form

### ISSUE THREAD

**Issue by alfonsusac** [alfonsusac/devscale-eventmaker#52]
- [x] Create a confirmation page: "Are you sure you want to delete this event?"
- [x] Show the event summary (all event details but no description and author) below it
  - [x] event title
  - [x] event date
- [x] Show 2 buttons: [ Delete ] [ Cancel ] below the event summary
- [x] Create a "back" button that redirects to /dashboard

<img width="566" alt="image" src="https://github.com/alfonsusac/devscale-eventmaker/assets/20208219/92ffc7bf-23d2-4cee-a6ba-7f4795529512">

**Comment by alfonsusac** [comment]
Updated the requirement

**Comment by ilmi** [comment]
done
