### ISSUE TITLE
Guest Header: conditionally render based on user session

### ISSUE THREAD

**Issue by alfonsusac** [alfonsusac/devscale-eventmaker#58]
In `<Header/>`

- [x] Header accepts “session” props.
- [ ]  Header now conditionally render [ login / regiser ] or [ go to dashboard ] button based on the session data:
    - Login components: `LoginForm.jsx`
    - Register components: `RegisterForm.jsx`

- [x] use the session() function in page.js that uses the header `<Header/>` component
- [x] pass the session to `<Header />`

**Comment by alfonsusac** [comment]
Additional Task: 

- [ ] wrap the usage of session() with `try..catch..`

example: 
```tsx
let userSession
try {
  userSession = session()
} catch(e) {

}

return (
  <Header session={session} /> 
)
```
Sekarang ada kemungkinan session === undefined. Jadi harus di cek di komponen <Header />

**Comment by ttnsy** [comment]
> Additional Task:
> 
> * [ ]  wrap the usage of session() with `try..catch..`
> 
> example:
> 
> ```tsx
> let userSession
> try {
>   userSession = session()
> } catch(e) {
> 
> }
> 
> return (
>   <Header session={session} /> 
> )
> ```
> 
> Sekarang ada kemungkinan session === undefined. Jadi harus di cek di komponen

Hello @alfonsusac,
To address this issue, rather than using tryCatch, i updated `session()` function decode & return values based on `token` (see 6f74509a7af32bdad473caca1f7f7b290c87418a). This fix does the job without resorting to tryCatch. But let me know if you reckon this step is needed.

**Comment by alfonsusac** [comment]
@ttnsy Please tag me on discord. I don't have push notification on GitHub
