### ISSUE TITLE
bug: user doesn't redirected to home/dashboard after successfully logged in.

### ISSUE THREAD

**Issue by ttnsy** [alfonsusac/devscale-eventmaker#72]
## How to reproduce:
- In `/login` page, after user has successfully logged in, user stays in the page rather than redirected to home/dashboard.

## Expected behaviour:
- User to be redirected to either home/dashboard after successfully logged in

**Comment by alfonsusac** [comment]
Noted. Feel free for anybody to assign to this issue

**Comment by alfonsusac** [comment]
@ttnsy can you assign a branch for this issue when you are working on it?
<img width="428" alt="image" src="https://github.com/alfonsusac/devscale-eventmaker/assets/20208219/187fd88f-6641-4639-978d-b59474b81a83">
